// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logicalClock.proto

#include "logicalClock.pb.h"
#include "logicalClock.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace logicalclockservice {

static const char* LogicalClockService_method_names[] = {
  "/logicalclockservice.LogicalClockService/SendMessage",
};

std::unique_ptr< LogicalClockService::Stub> LogicalClockService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LogicalClockService::Stub> stub(new LogicalClockService::Stub(channel, options));
  return stub;
}

LogicalClockService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(LogicalClockService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LogicalClockService::Stub::SendMessage(::grpc::ClientContext* context, const ::logicalclockservice::LogicalClockTime& request, ::logicalclockservice::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::logicalclockservice::LogicalClockTime, ::logicalclockservice::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void LogicalClockService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::logicalclockservice::LogicalClockTime* request, ::logicalclockservice::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::logicalclockservice::LogicalClockTime, ::logicalclockservice::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void LogicalClockService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::logicalclockservice::LogicalClockTime* request, ::logicalclockservice::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::logicalclockservice::Reply>* LogicalClockService::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::logicalclockservice::LogicalClockTime& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::logicalclockservice::Reply, ::logicalclockservice::LogicalClockTime, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::logicalclockservice::Reply>* LogicalClockService::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::logicalclockservice::LogicalClockTime& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

LogicalClockService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LogicalClockService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LogicalClockService::Service, ::logicalclockservice::LogicalClockTime, ::logicalclockservice::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LogicalClockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::logicalclockservice::LogicalClockTime* req,
             ::logicalclockservice::Reply* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
}

LogicalClockService::Service::~Service() {
}

::grpc::Status LogicalClockService::Service::SendMessage(::grpc::ServerContext* context, const ::logicalclockservice::LogicalClockTime* request, ::logicalclockservice::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace logicalclockservice

